from __future__ import annotations

DISPLAY_NAME = "AndroidTestClii"
SLUG = "androidtestclii"

COMMAND_NAME = "AndroidTestClii"
COMMAND_ALIAS = "androidtestclii"
LEGACY_COMMAND_NAMES = ("android-cli", "u2cli")

TOOL_PREFIX = "AndroidTestClii_"
LEGACY_TOOL_PREFIXES = ("android_cli_", "u2cli_")

SESSION_ENV = "ANDROIDTESTCLII_SESSION_PATH"
LEGACY_SESSION_ENV = "U2CLI_SESSION_PATH"

PI_REQUIRE_AGENT_ROLE_ENV = "ANDROIDTESTCLII_PI_REQUIRE_AGENT_ROLE"
LEGACY_PI_REQUIRE_AGENT_ROLE_ENV = "U2CLI_PI_REQUIRE_AGENT_ROLE"

BIN_ENV = "ANDROIDTESTCLII_BIN"
LEGACY_BIN_ENV = "ANDROID_CLI_BIN"
U2CLI_BIN_ENV = "U2CLI_BIN"

ALERT_BUTTONS_ENV = "ANDROIDTESTCLII_ALERT_BUTTONS"
LEGACY_ALERT_BUTTONS_ENV = "U2CLI_ALERT_BUTTONS"

SNAPSHOT_HELPER_APK_ENV = "ANDROIDTESTCLII_ANDROID_SNAPSHOT_HELPER_APK"
LEGACY_SNAPSHOT_HELPER_APK_ENV = "U2CLI_ANDROID_SNAPSHOT_HELPER_APK"

SNAPSHOT_JAR_ENV = "ANDROIDTESTCLII_ANDROID_SNAPSHOT_JAR"
LEGACY_SNAPSHOT_JAR_ENV = "U2CLI_ANDROID_SNAPSHOT_JAR"
